### ISSUE TITLE
Possible to use this to import artists/albums into Lidarr?

### ISSUE THREAD

**Issue by mptpro** [sirk123au/ArrTools#11]
I would be great if this could import/add artists and albums from a CSV file, or any other type of text file. I currently have all of my YouTube Music artists/albums/songs (over 20k) in a spreadsheet and I'd like to get them into Lidarr.

**Comment by sirk123au** [comment]
I do have a lidarr import script in this repo

**Comment by mptpro** [comment]
Wow! you do?  Let me look..... thanks

**Comment by sirk123au** [comment]
lidarr_add_from_list.py is the script

**Comment by mptpro** [comment]
thank you!

**Comment by mptpro** [comment]
I'm sorry to bug, but I am having the following problem when running the lidarr add from script...

```
Traceback (most recent call last):
  File "D:\!temp\arrtools-master\l.py", line 107, in <module>
    main()
  File "D:\!temp\arrtools-master\l.py", line 91, in main
    s = sorted(m, key=lambda row:(row), reverse=False)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4297: character maps to <undefined>
```

I have python3 installed and did the pip requirements updates.

In the config.ini file I have entered:
API = my lidarr api
base url: not sure if I have it in the correct format, I've tried http://localhost:8686/ and http://192.168.86.23:8686/
I left the rootfolerpath empty

Also, the lidarr backup script returned an empty .csv file (used both variations of the base url).

Thanks again for your help - your scripts are exactly what I am looing for. I'm moving my YouTube Music over to Lidarr and I've successfully created a CSV file of artists/albums/songs but now I need to get them into Lidarr.

**Comment by sirk123au** [comment]
Can you give me a sample of the CSV file

**Comment by mptpro** [comment]
of course. Here it is....

https://drive.google.com/file/d/1r4amJjjhDwB0zP3L5-J4QYtsS2ysvK8H/view?usp=sharing

**Comment by sirk123au** [comment]
This script only imports artist and adds all albums. So the CSV only needs artist

**Comment by mptpro** [comment]
Thank you. I think I fixed the csv file and made some progress but now this error...

```
ar3.csvPS D:\!temp\arrtools-master> .\l.py ar3.csv
[INFO] Found 3347 Artists in ar3.csv. :)
Traceback (most recent call last):
  File "D:\!temp\arrtools-master\l.py", line 107, in <module>
    main()
  File "D:\!temp\arrtools-master\l.py", line 101, in main
    else: log.error("There was an error reading {} Details".format(title))
NameError: name 'title' is not defined
```

Here is my updated CSV file....

https://drive.google.com/file/d/1RUT9uxzVzioX5bFsC5wiISOTIwKfaNbP/view?usp=sharing


Thank you again for all your help!

**Comment by sirk123au** [comment]
Sorry the CSV first row header has to be title I will have a look for you today

**Comment by mptpro** [comment]
Thanks.  I upated csv file to make the first row "title" but I get the same error.

here is csv file: https://drive.google.com/file/d/138OvQwubQ9sz5MTlU4jbAKpEi83lBGye/view?usp=sharing

thanks again

**Comment by sirk123au** [comment]
sorry i am having a look now and fixing all the issues

**Comment by sirk123au** [comment]
so i have fixed the script works with the list you provided. you just have to download the script again and the header has to be artist,foreignArtistId 

it will auto search all albums too so if you don't want that set monitored to false

also rootfolderpath cannot be empty

**Comment by sirk123au** [comment]
and the header has to be artist,foreignArtistId

**Comment by mptpro** [comment]
THanks. Still doesn't work but I'm sure it's something Im doing wrong.  Here's what I did.

I upated the csv header to:

- artist ,foreignArtistId
- artist, foreign , ArtistId

I tried both above since I wasn't sure if "foreign" and "ArtistID" where supposed to be two differnt column.

(Note: I had removed the album column since I'm ok with just importing "artists").


And I changed the config file to:

```
[lidarr]
api_key = XXXX
baseurl = localhost:8686/
rootfolderpath = D:\music
```

I downloaded your updated script and the error I get is:
```

PS D:\!temp\arrtools-master> .\l.py artists.csv
  File "D:\!temp\arrtools-master\l.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
PS D:\!temp\arrtools-master> .\l.py artists.csv
  File "D:\!temp\arrtools-master\l.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax


```


(Note: I just renamed your script to "l.py" to make it easier to type).

THanks again for your help.  PS I'm trying to "buy you coffee" but it's not working. If you provide me your PayPal I'll send you $5.

**Comment by sirk123au** [comment]
The Header is this artist ,foreignArtistId it has to be on the first line of the csv like this 

```
artist,foreignArtistId
.38 Special
+44
10cc
10CC
16 Bit Lolitas
16ats
1788-L
2 DJ's and One
```

This is what your config should look like 

```
[lidarr]
api_key = XXXX
baseurl = http://localhost:8686/
rootfolderpath = D:\music
```

The error you are getting is that you have just tried to download the html file not the raw script 
here is a direct link to the raw file 
[https://raw.githubusercontent.com/sirk123au/ArrTools/master/lidarr_add_from_list.py](https://raw.githubusercontent.com/sirk123au/ArrTools/master/lidarr_add_from_list.py)


with regards to the Buy Me a Coffee link seems to work for me can you tell me what the error is so i can look into it

Thanks

**Comment by mptpro** [comment]
Ok, making progress!  I edited my config as you stated and re-downloaded the .py script and it's getting alot furter but now I'm getting the errors below....

```

PS D:\!temp\arrtools-master> .\lidarr_add_from_list.py artists.csv
[INFO] Found 3338 Artists in artists.csv. :)
[ERROR] .38 Special Not found, Not added to Lidarr.
[ERROR] Sorry. We couldn't find (+44)
[ERROR] (+44) Not found, Not added to Lidarr.
[ERROR] +44 Not found, Not added to Lidarr.
[ERROR] 10cc Not found, Not added to Lidarr.
[ERROR] 10CC Not found, Not added to Lidarr.
[ERROR] 16 Bit Lolitas Not found, Not added to Lidarr.
[ERROR] Sorry. We couldn't find 16ats
[ERROR] 16ats Not found, Not added to Lidarr.
[ERROR] 1788-L Not found, Not added to Lidarr.
[ERROR] 2 DJ's and One Not found, Not added to Lidarr.
[ERROR] 3 Doors Down Not found, Not added to Lidarr.
[ERROR] 3-11 Porter Not found, Not added to Lidarr.
[ERROR] 30 Seconds to Mars Not found, Not added to Lidarr.
[ERROR] 30 Seconds To Mars Not found, Not added to Lidarr.
[ERROR] 4 Non Blondes Not found, Not added to Lid
```

As for paypal i think it's on my end. I've contacted paypal. It keeps getting declined by there is no reason for that. If you have anoter way for me to "buy you coffee" I'd be happy to do so!

**Comment by sirk123au** [comment]
[https://paypal.me/KMComputers?locale.x=en_AU](https://paypal.me/KMComputers?locale.x=en_AU)

here is my direct paypal link if you want.

```
python lidarr_add_from_list.py artists.csv
[INFO] Found 3337 Artists in artists.csv. :)
[INFO] .38 Special Added to Lidarr :)
[INFO] +44 Added to Lidarr :)
[INFO] 10cc Added to Lidarr :)
[INFO] 10CC already Exists in Lidarr.
[INFO] 16 Bit Lolitas Added to Lidarr :)
[ERROR] Sorry. We couldn't find 16ats
[INFO] 1788-L Added to Lidarr :)
[INFO] 2 DJ's and One Added to Lidarr :)
```

this is the results from my win10 machine 

can you add your log file so i can see  what the connection error is thanks 

if you use discord we can chat directly
https://discord.gg/zNGychEt

**Comment by mptpro** [comment]
I sent you $10 via PayPal from mptpro

Here is my log: https://drive.google.com/file/d/1TeKq_D-MI6rLXFtnJU2K7OottfAB9lsa/view?usp=sharing

I am on discord, but currently I'm off and on on the computer.

**Comment by sirk123au** [comment]
are you using the latest Lidarr? 
![image](https://user-images.githubusercontent.com/6962647/118441055-f497d500-b72b-11eb-9abb-fd2d2b7e1c45.png)

Have you set any auth or Url Base?

and thank you for that i do not expect to be paid i do this as a hobby.

**Comment by sirk123au** [comment]
ok i think i know what the issue may be can you please download the script again as i have added a heap of updates

https://github.com/sirk123au/ArrTools/raw/master/lidarr_add_from_list.py


when you run the script you have to use this command 
`python lidarr_add_from_list.py artists.csv`


I think your api key maybe wrong just from these lines in you log 

```
2021-05-16 22:57:15,090 [DEBUG]  http://localhost:8686 "POST //api/v1/artist HTTP/1.1" 303 None
2021-05-16 22:57:15,093 [DEBUG]  http://localhost:8686 "GET /login?returnUrl=//api/v1/artist HTTP/1.1" 200 None
```


With the config you need to remove the trailing / too

```
[lidarr]
api_key = XXXX
baseurl = http://localhost:8686 <-- Here
rootfolderpath = D:\music
```

**Comment by mptpro** [comment]
it worked!  THANK YOU SOOOO MUCH!

**Comment by sirk123au** [comment]
This script is not 100% accurate there is a lot of repeated artist in your csv and i tried to make it as quick as possible but it is a bit slow
